Localize Strings in JavaScript
dkd/ffcrm_attachments pull request #5
Opened 2016-12-19 17:45 UTC by klyonrad

This adds localized strings to the UI elements that are generated with JavaScript.
It also fixes the display of error messages.

# Test Plan

## without error

1. Set locale to `de`
2. Open Entity Edit form
3. Add two attachmets
4. Expected: both rows show _Beschreibung_ and _Löschen_

## with error

1. Set locale to `de`
2. Open Entity Edit form
3. Add attachment with file size over 10MB (or whatever is set in settings)
4. Expected: Message _Datei ist zu groß._

2016-12-19 18:51 UTC, zlorfi requested changes

2016-12-19 18:51 UTC, zlorfi commented on app/views/attachments/_attachments_new.html.haml
> +  window.I18nForAttachments = #{(current_translations.to_json.html_safe)};
duplicate line?

2016-12-20 09:33 UTC, klyonrad commented on app/views/attachments/_attachments_new.html.haml
> +  window.I18nForAttachments = #{(current_translations.to_json.html_safe)};
I do not remember writing this

2016-12-20 09:35 UTC, zlorfi approved these changes

2016-12-20 09:36 UTC, merged